/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.brunner.service;

import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;

import org.apache.ibatis.session.SqlSession;
import org.springframework.stereotype.Component;

import com.brunner.service.SVC_AuthorityGroup.Constants_AuthorityGroup;
import com.brunner.service.SVC_AuthorityGroup.Messages_AuthorityGroup;
import com.brunner.service.dao.TB_COR_AUTHORITY_GROUP_PROGRAM;
import com.brunner.service.util.Constants;
import com.brunner.service.util.ExceptionUtil;
import com.brunner.service.util.MapUtil;
import com.brunner.service.util.Messages;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;

import mw.utility.BrunnerLogger;

@Component
public class SVC_AuthorityGroupProgram {
	private final String CLASS = this.getClass().getName();
	private final Logger logger = BrunnerLogger.getLogger(CLASS);

	@PostConstruct
	public void init() {
		System.out.println(String.format("init bean [%s]", this.getClass().getName()));
	}	
	
	public JsonObject TXN_AuthorityGroupProgram_registerAuthorityGroupProgram(
			SqlSession session, 
			JsonObject request) {
		
		final String METHOD = new Exception().getStackTrace()[0].getMethodName();
		
		JsonObject reply = null;
		String resultCode = Constants_AuthorityGroupProgram.resultCode_systemException;
		String resultMessage = Constants_AuthorityGroupProgram.emptyString;
		String txnId = request.get(Constants.msgFieldName_inputData).getAsJsonObject().get(Constants.msgFieldName_txnId).getAsString();
		
   		logger.log(Level.INFO, String.format(Messages_AuthorityGroup.msg_startService, 
   				txnId, 
   				CLASS, 
   				METHOD));   		

   		int nEffected = 0;
   		
   		try {
    		List<HashMap<String, Object>> rows = TB_COR_AUTHORITY_GROUP_PROGRAM.select_02(
    				session,
    				txnId,
    				request.get(Constants_AuthorityGroupProgram.msgFieldName_inputData).getAsJsonObject().get("systemCode").getAsString(), 
    				request.get(Constants_AuthorityGroupProgram.msgFieldName_inputData).getAsJsonObject().get("authorityGroupId").getAsString(),
    				request.get(Constants_AuthorityGroupProgram.msgFieldName_inputData).getAsJsonObject().get("programId").getAsString()
    				);
			
   			if(rows.size() > 0) {
				// 이미 있음 
	   			nEffected = TB_COR_AUTHORITY_GROUP_PROGRAM.update_01(
	   					session,
	   					txnId,
	    				request.get(Constants_AuthorityGroup.msgFieldName_inputData).getAsJsonObject().get("systemCode").getAsString(), 
	    				request.get(Constants_AuthorityGroup.msgFieldName_inputData).getAsJsonObject().get("userId").getAsString(),
	    				request.get(Constants_AuthorityGroup.msgFieldName_inputData).getAsJsonObject().get("authorityGroupId").getAsString(),
	    				request.get(Constants_AuthorityGroup.msgFieldName_inputData).getAsJsonObject().get("programId").getAsString()
	    				);
	
				if(nEffected == 1) {
	    			resultCode = Constants_AuthorityGroup.resultCode_success;
	    			resultMessage = String.format(Messages_AuthorityGroupProgram.msg_successfullyFinished, CLASS, METHOD);
				} else if(nEffected == 0) {
	    			resultCode = Constants_AuthorityGroup.resultCode_failToUpdateData;
	    			resultMessage = String.format(Messages_AuthorityGroupProgram.msg_failToUpdateData);
				} else {
					// 오류: 여러건 변경
	    			resultCode = Constants_AuthorityGroup.resultCode_failToUpdateData;
	    			resultMessage = String.format(Messages_AuthorityGroupProgram.msg_affectedDataMoreThanOneRow);
				}
   			} else {
	   			nEffected = TB_COR_AUTHORITY_GROUP_PROGRAM.insert_01(
	   					session,
	   					txnId,
	    				request.get(Constants_AuthorityGroupProgram.msgFieldName_inputData).getAsJsonObject().get("systemCode").getAsString(), 
	    				request.get(Constants_AuthorityGroupProgram.msgFieldName_inputData).getAsJsonObject().get("userId").getAsString(),
	    				request.get(Constants_AuthorityGroupProgram.msgFieldName_inputData).getAsJsonObject().get("authorityGroupId").getAsString(),
	    				request.get(Constants_AuthorityGroupProgram.msgFieldName_inputData).getAsJsonObject().get("programId").getAsString(),
	    				"Y"
	    				);
	
				if(nEffected == 1) {
	    			resultCode = Constants_AuthorityGroupProgram.resultCode_success;
	    			resultMessage = String.format(Messages_AuthorityGroupProgram.msg_successfullyFinished, CLASS, METHOD);
				} else if(nEffected == 0) {
					// 오류: 인서트 실패
	    			resultCode = Constants_AuthorityGroupProgram.resultCode_failToUpdateData;
	    			resultMessage = String.format(Messages_AuthorityGroupProgram.msg_failToUpdateData);
				} else {
					// 오류: 여러건 인서트
	    			resultCode = Constants_AuthorityGroupProgram.resultCode_failToUpdateData;
	    			resultMessage = String.format(Messages_AuthorityGroupProgram.msg_affectedDataMoreThanOneRow);
				}
   			}
		} catch (Exception e) {
			resultCode = Constants_AuthorityGroupProgram.resultCode_systemException;
			resultMessage = ExceptionUtil.getFullMessage(e);
			logger.log(Level.SEVERE, resultMessage);
		}
		finally {
			reply = new JsonObject();
			reply.addProperty(Constants.msgFieldName_txnId, txnId);
			reply.addProperty(Constants.msgFieldName_resultCode, resultCode);
			reply.addProperty(Constants.msgFieldName_resultMessage, resultMessage);

			logger.log(Level.INFO, String.format(Messages_AuthorityGroup.msg_endService, 
	   				txnId, 
	   				CLASS, 
	   				METHOD));
		}
		return reply;
    }
	
	public JsonObject TXN_AuthorityGroupProgram_unregisterAuthorityGroupProgram(
			SqlSession session, 
			JsonObject request) {
		final String METHOD = new Exception().getStackTrace()[0].getMethodName();
		
		JsonObject reply = null;
		String resultCode = Constants_AuthorityGroupProgram.resultCode_systemException;
		String resultMessage = Constants_AuthorityGroupProgram.emptyString;
		String txnId = request.get(Constants.msgFieldName_inputData).getAsJsonObject().get(Constants.msgFieldName_txnId).getAsString();
		
   		logger.log(Level.INFO, String.format(Messages_AuthorityGroup.msg_startService, 
   				txnId, 
   				CLASS, 
   				METHOD));   	

   		int nEffected = 0;
   		
   		try {
    		List<HashMap<String, Object>> rows = TB_COR_AUTHORITY_GROUP_PROGRAM.select_02(
    				session,
    				txnId,
    				request.get(Constants_AuthorityGroupProgram.msgFieldName_inputData).getAsJsonObject().get("systemCode").getAsString(), 
    				request.get(Constants_AuthorityGroupProgram.msgFieldName_inputData).getAsJsonObject().get("authorityGroupId").getAsString(),
    				request.get(Constants_AuthorityGroupProgram.msgFieldName_inputData).getAsJsonObject().get("programId").getAsString()
    				);
			
   			if(rows.size() > 0) {
	   			nEffected = TB_COR_AUTHORITY_GROUP_PROGRAM.update_02(
	   					session,
	   					txnId,
	    				request.get(Constants_AuthorityGroupProgram.msgFieldName_inputData).getAsJsonObject().get("systemCode").getAsString(), 
	    				request.get(Constants_AuthorityGroupProgram.msgFieldName_inputData).getAsJsonObject().get("userId").getAsString(),
	    				request.get(Constants_AuthorityGroupProgram.msgFieldName_inputData).getAsJsonObject().get("authorityGroupId").getAsString(),
	    				request.get(Constants_AuthorityGroupProgram.msgFieldName_inputData).getAsJsonObject().get("programId").getAsString()
	    				);
	
				if(nEffected == 1) {
	    			resultCode = Constants_AuthorityGroupProgram.resultCode_success;
	    			resultMessage = String.format(Messages_AuthorityGroupProgram.msg_successfullyFinished, CLASS, METHOD);
				} else if(nEffected == 0) {
					// 오류: 업데이트 실패
	    			resultCode = Constants_AuthorityGroupProgram.resultCode_failToUpdateData;
	    			resultMessage = String.format(Messages_AuthorityGroupProgram.msg_failToUpdateData);
				} else {
					// 오류: 여러건 변경
	    			resultCode = Constants_AuthorityGroupProgram.resultCode_failToUpdateData;
	    			resultMessage = String.format(Messages_AuthorityGroupProgram.msg_affectedDataMoreThanOneRow);
				}
   			} else {
    			resultCode = Constants_AuthorityGroupProgram.resultCode_noDataFound;
    			resultMessage = String.format(Messages_AuthorityGroupProgram.msg_notExistAuthorityGroupProgram, 
    					request.get(Constants_AuthorityGroupProgram.msgFieldName_inputData).getAsJsonObject().get("authorityGroupId").getAsString(),
    					request.get(Constants_AuthorityGroupProgram.msgFieldName_inputData).getAsJsonObject().get("programId").getAsString());
   			}
		} catch (Exception e) {
			resultCode = Constants_AuthorityGroupProgram.resultCode_systemException;
			resultMessage = ExceptionUtil.getFullMessage(e);
			logger.log(Level.SEVERE, resultMessage);
		}
		finally {
			reply = new JsonObject();
			reply.addProperty(Constants.msgFieldName_txnId, txnId);
			reply.addProperty(Constants.msgFieldName_resultCode, resultCode);
			reply.addProperty(Constants.msgFieldName_resultMessage, resultMessage);

			logger.log(Level.INFO, String.format(Messages_AuthorityGroup.msg_endService, 
	   				txnId, 
	   				CLASS, 
	   				METHOD));
		}
		return reply;
    }	

	public JsonObject TXN_AuthorityGroupProgram_viewAuthorityGroupProgramList(
			SqlSession session, 
			JsonObject request) {
		final String METHOD = new Exception().getStackTrace()[0].getMethodName();
		
		JsonObject reply = null;
		String resultCode = Constants_AuthorityGroupProgram.resultCode_systemException;
		String resultMessage = Constants_AuthorityGroupProgram.emptyString;
		String txnId = request.get(Constants.msgFieldName_inputData).getAsJsonObject().get(Constants.msgFieldName_txnId).getAsString();
		
   		logger.log(Level.INFO, String.format(Messages_AuthorityGroup.msg_startService, 
   				txnId, 
   				CLASS, 
   				METHOD));   		

   		List<HashMap<String, Object>> rows = null;
   		
   		try {
    		rows = TB_COR_AUTHORITY_GROUP_PROGRAM.select_01(
    				session,
    				txnId,
    				MapUtil.getNullableString(request.get(Constants_AuthorityGroupProgram.msgFieldName_inputData).getAsJsonObject(), "systemCode"), 
    				String.format("%s", MapUtil.getNullableString(request.get(Constants_AuthorityGroupProgram.msgFieldName_inputData).getAsJsonObject(), "authorityGroupId")),
    				"%" + String.format("%s", MapUtil.getNullableString(request.get(Constants_AuthorityGroupProgram.msgFieldName_inputData).getAsJsonObject(), "programId")) + "%"
    				);

    		JsonArray jAuthorityGroupList = new JsonArray();
    		for(int rowIndex = 0; rowIndex < rows.size(); rowIndex++) {
    			JsonObject jRow = new JsonObject();
    			HashMap<String, Object> row = rows.get(rowIndex);
       			jRow.addProperty("programId", MapUtil.getNullableString(row, "PROGRAM_ID"));
       			jRow.addProperty("parentProgramId", MapUtil.getNullableString(row, "PARENT_PROGRAM_ID"));
       			jRow.addProperty("displaySeq", MapUtil.getNullableString(row, "DISPLAY_SEQ"));
    			jRow.addProperty("programName", MapUtil.getNullableString(row, "PROGRAM_NAME"));
    			jRow.addProperty("programClassPath", MapUtil.getNullableString(row, "PROGRAM_CLASS_PATH"));
    			
    			jAuthorityGroupList.add(jRow);
    		}
    		resultCode = Constants_AuthorityGroupProgram.resultCode_success;
    		
    		reply = new JsonObject();
    		reply.addProperty(Constants.msgFieldName_txnId, txnId);
			reply.add("authorityGroupProgramList", jAuthorityGroupList);
			reply.addProperty(Constants.msgFieldName_resultCode, resultCode);
			reply.addProperty(Constants.msgFieldName_resultMessage, resultMessage);
    		
		} catch (Exception e) {
			resultCode = Constants_AuthorityGroupProgram.resultCode_systemException;
			resultMessage = ExceptionUtil.getFullMessage(e);
			logger.log(Level.SEVERE, resultMessage);
		}
		finally {

			logger.log(Level.INFO, String.format(Messages_AuthorityGroup.msg_endService, 
	   				txnId, 
	   				CLASS, 
	   				METHOD));
		}
		return reply;
    }	

	public JsonObject TXN_AuthorityGroupProgram_viewUserProgramList(
			SqlSession session, 
			JsonObject request) {
		final String METHOD = new Exception().getStackTrace()[0].getMethodName();
		
		JsonObject reply = null;
		String resultCode = Constants_AuthorityGroupProgram.resultCode_systemException;
		String resultMessage = Constants_AuthorityGroupProgram.emptyString;
		String txnId = request.get(Constants.msgFieldName_inputData).getAsJsonObject().get(Constants.msgFieldName_txnId).getAsString();
		
   		logger.log(Level.INFO, String.format(Messages_AuthorityGroup.msg_startService, 
   				txnId, 
   				CLASS, 
   				METHOD));   	

   		List<HashMap<String, Object>> rows = null;
   		
   		try {
   			String parentProgramId = MapUtil.getNullableString(request.get(Constants_AuthorityGroupProgram.msgFieldName_inputData).getAsJsonObject(), "parentProgramId");
   			if(parentProgramId == null || parentProgramId.isEmpty() == true)
	    		rows = TB_COR_AUTHORITY_GROUP_PROGRAM.select_03(
	    				session,
	    				txnId,
	    				MapUtil.getNullableString(request.get(Constants_AuthorityGroupProgram.msgFieldName_inputData).getAsJsonObject(), "systemCode"), 
	    				String.format("%s", MapUtil.getNullableString(request.get(Constants_AuthorityGroupProgram.msgFieldName_inputData).getAsJsonObject(), "userId")),
	    				String.format("%s", MapUtil.getNullableString(request.get(Constants_AuthorityGroupProgram.msgFieldName_inputData).getAsJsonObject(), "parentProgramId"))
	    				);
   			else
	    		rows = TB_COR_AUTHORITY_GROUP_PROGRAM.select_04(
	    				session,
	    				txnId,
	    				MapUtil.getNullableString(request.get(Constants_AuthorityGroupProgram.msgFieldName_inputData).getAsJsonObject(), "systemCode"), 
	    				String.format("%s", MapUtil.getNullableString(request.get(Constants_AuthorityGroupProgram.msgFieldName_inputData).getAsJsonObject(), "userId")),
	    				String.format("%s", MapUtil.getNullableString(request.get(Constants_AuthorityGroupProgram.msgFieldName_inputData).getAsJsonObject(), "parentProgramId"))
	    				);
   				

    		JsonArray jAuthorityGroupList = new JsonArray();
    		for(int rowIndex = 0; rowIndex < rows.size(); rowIndex++) {
    			JsonObject jRow = new JsonObject();
    			HashMap<String, Object> row = rows.get(rowIndex);
       			jRow.addProperty("programId", MapUtil.getNullableString(row, "PROGRAM_ID"));
       			jRow.addProperty("displaySeq", MapUtil.getNullableString(row, "DISPLAY_SEQ"));
    			jRow.addProperty("programName", MapUtil.getNullableString(row, "PROGRAM_NAME"));
    			jRow.addProperty("programClassPath", MapUtil.getNullableString(row, "PROGRAM_CLASS_PATH"));
    			
    			jAuthorityGroupList.add(jRow);
    		}
    		resultCode = Constants_AuthorityGroupProgram.resultCode_success;
    		
    		reply = new JsonObject();
    		reply.addProperty(Constants.msgFieldName_txnId, txnId);
			reply.add("programList", jAuthorityGroupList);
			reply.addProperty(Constants.msgFieldName_resultCode, resultCode);
			reply.addProperty(Constants.msgFieldName_resultMessage, resultMessage);    		
		} catch (Exception e) {
			resultCode = Constants_AuthorityGroupProgram.resultCode_systemException;
			resultMessage = ExceptionUtil.getFullMessage(e);
			logger.log(Level.SEVERE, resultMessage);
		}
		finally {

			logger.log(Level.INFO, String.format(Messages_AuthorityGroup.msg_endService, 
	   				txnId, 
	   				CLASS, 
	   				METHOD));
		}
		return reply;
	}
	
	public class Constants_AuthorityGroupProgram extends Constants {
	}	

	public static class Messages_AuthorityGroupProgram extends Messages {
		public static String msg_alreadyExistAuthorityGroupProgram = "The authorityGroup-Program [%s]-[%s] already exist.";
		public static String msg_notExistAuthorityGroupProgram = "The authorityGroup-Program [%s]-[%s] not exist.";

	}	
}
