/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.brunner.service;

import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;

import org.apache.ibatis.session.SqlSession;
import org.springframework.stereotype.Component;

import com.brunner.service.dao.TB_COR_AUTHORITY_GROUP_MST;
import com.brunner.service.util.Constants;
import com.brunner.service.util.ExceptionUtil;
import com.brunner.service.util.MapUtil;
import com.brunner.service.util.Messages;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;

import mw.utility.BrunnerLogger;

@Component
public class SVC_AuthorityGroup {
	private final String CLASS = this.getClass().getName();
	private final Logger logger = BrunnerLogger.getLogger(CLASS);

	@PostConstruct
	public void init() {
		System.out.println(String.format("init bean [%s]", this.getClass().getName()));
	}		
	
	public JsonObject TXN_AuthorityGroup_registerAuthorityGroup(
			SqlSession session, 
			JsonObject request) {
		
		final String METHOD = new Exception().getStackTrace()[0].getMethodName();
		
		JsonObject reply = null;
		String resultCode = Constants_AuthorityGroup.resultCode_systemException;
		String resultMessage = Constants_AuthorityGroup.emptyString;
		String txnId = request.get(Constants.msgFieldName_inputData).getAsJsonObject().get(Constants.msgFieldName_txnId).getAsString();
		
   		logger.log(Level.INFO, 
   				String.format(Messages_AuthorityGroup.msg_startService, 
   				txnId, 
   				CLASS, 
   				METHOD));   		

   		int nEffected = 0;
   		
   		try {
    		List<HashMap<String, Object>> rows = TB_COR_AUTHORITY_GROUP_MST.select_02(
    				session,
    				txnId,
    				request.get(Constants_AuthorityGroup.msgFieldName_inputData).getAsJsonObject().get("systemCode").getAsString(), 
    				request.get(Constants_AuthorityGroup.msgFieldName_inputData).getAsJsonObject().get("authorityGroupId").getAsString()
    				);
			
   			if(rows.size() > 0) {
	   			nEffected = TB_COR_AUTHORITY_GROUP_MST.update_01(
	   					session,
	   					txnId,
	    				request.get(Constants_AuthorityGroup.msgFieldName_inputData).getAsJsonObject().get("systemCode").getAsString(), 
	    				request.get(Constants_AuthorityGroup.msgFieldName_inputData).getAsJsonObject().get("userId").getAsString(),
	    				request.get(Constants_AuthorityGroup.msgFieldName_inputData).getAsJsonObject().get("authorityGroupId").getAsString(),
	    				request.get(Constants_AuthorityGroup.msgFieldName_inputData).getAsJsonObject().get("authorityGroupName").getAsString()
	    				);
	
				if(nEffected == 1) {
	    			resultCode = Constants_AuthorityGroup.resultCode_success;
	    			resultMessage = String.format(Messages_AuthorityGroup.msg_successfullyFinished, CLASS, METHOD);
				} else if(nEffected == 0) {
	    			resultCode = Constants_AuthorityGroup.resultCode_failToUpdateData;
	    			resultMessage = String.format(Messages_AuthorityGroup.msg_failToUpdateData);
				} else {
					// 오류: 여러건 변경
	    			resultCode = Constants_AuthorityGroup.resultCode_failToUpdateData;
	    			resultMessage = String.format(Messages_AuthorityGroup.msg_affectedDataMoreThanOneRow);
				}
   			} else {
	   			nEffected = TB_COR_AUTHORITY_GROUP_MST.insert_01(
	   					session,
	   					txnId,
	    				request.get(Constants_AuthorityGroup.msgFieldName_inputData).getAsJsonObject().get("systemCode").getAsString(), 
	    				request.get(Constants_AuthorityGroup.msgFieldName_inputData).getAsJsonObject().get("userId").getAsString(),
	    				request.get(Constants_AuthorityGroup.msgFieldName_inputData).getAsJsonObject().get("authorityGroupId").getAsString(),
	    				request.get(Constants_AuthorityGroup.msgFieldName_inputData).getAsJsonObject().get("authorityGroupName").getAsString(),
	    				"Y"
	    				);
	
				if(nEffected == 1) {
	    			resultCode = Constants_AuthorityGroup.resultCode_success;
	    			resultMessage = String.format(Messages_AuthorityGroup.msg_successfullyFinished, CLASS, METHOD);
				} else if(nEffected == 0) {
					// 오류: 변경행 없음
	    			resultCode = Constants_AuthorityGroup.resultCode_failToUpdateData;
	    			resultMessage = String.format(Messages_AuthorityGroup.msg_failToUpdateData);
				} else {
					// 오류: 여러건 변경
	    			resultCode = Constants_AuthorityGroup.resultCode_failToUpdateData;
	    			resultMessage = String.format(Messages_AuthorityGroup.msg_affectedDataMoreThanOneRow);
				}
   			}
		} catch (Exception e) {
			resultCode = Constants_AuthorityGroup.resultCode_systemException;
			resultMessage = ExceptionUtil.getFullMessage(e);
			logger.log(Level.SEVERE, resultMessage);
		}
		finally {
			reply = new JsonObject();
			reply.addProperty(Constants.msgFieldName_txnId, txnId);
			reply.addProperty(Constants.msgFieldName_resultCode, resultCode);
			reply.addProperty(Constants.msgFieldName_resultMessage, resultMessage);

			logger.log(Level.INFO, String.format(Messages_AuthorityGroup.msg_endService, 
	   				txnId, 
	   				CLASS, 
	   				METHOD));
		}
		return reply;
    }
	
	public JsonObject TXN_AuthorityGroup_unregisterAuthorityGroup(
			SqlSession session,
			JsonObject request) {
		
		final String METHOD = new Exception().getStackTrace()[0].getMethodName();
		
		JsonObject reply = null;
		String resultCode = Constants_AuthorityGroup.resultCode_systemException;
		String resultMessage = Constants_AuthorityGroup.emptyString;
		String txnId = request.get(Constants.msgFieldName_inputData).getAsJsonObject().get(Constants.msgFieldName_txnId).getAsString();
		
   		logger.log(Level.INFO, String.format(Messages_AuthorityGroup.msg_startService, 
   				txnId, 
   				CLASS, 
   				METHOD));   		

   		int nEffected = 0;
   		
   		try {
    		List<HashMap<String, Object>> rows = TB_COR_AUTHORITY_GROUP_MST.select_02(
    				session,
    				txnId,
    				request.get(Constants_AuthorityGroup.msgFieldName_inputData).getAsJsonObject().get("systemCode").getAsString(), 
    				request.get(Constants_AuthorityGroup.msgFieldName_inputData).getAsJsonObject().get("authorityGroupId").getAsString()
    				);
			
   			if(rows.size() > 0) {
	   			nEffected = TB_COR_AUTHORITY_GROUP_MST.update_02(
	   					session,
	   					txnId,
	    				request.get(Constants_AuthorityGroup.msgFieldName_inputData).getAsJsonObject().get("systemCode").getAsString(), 
	    				request.get(Constants_AuthorityGroup.msgFieldName_inputData).getAsJsonObject().get("userId").getAsString(),
	    				request.get(Constants_AuthorityGroup.msgFieldName_inputData).getAsJsonObject().get("authorityGroupId").getAsString()
	    				);
	
				if(nEffected == 1) {
	    			resultCode = Constants_AuthorityGroup.resultCode_success;
	    			resultMessage = String.format(Messages_AuthorityGroup.msg_successfullyFinished, CLASS, METHOD);
				} else if(nEffected == 0) {
					// 오류: 변경행 없음
	    			resultCode = Constants_AuthorityGroup.resultCode_failToUpdateData;
	    			resultMessage = String.format(Messages_AuthorityGroup.msg_failToUpdateData);
				} else {
					// 오류: 여러건 변경
	    			resultCode = Constants_AuthorityGroup.resultCode_failToUpdateData;
	    			resultMessage = String.format(Messages_AuthorityGroup.msg_affectedDataMoreThanOneRow);
				}
   			} else {
    			resultCode = Constants_AuthorityGroup.resultCode_noDataFound;
    			resultMessage = String.format(Messages_AuthorityGroup.msg_notExistAuthorityGroup, 
    					request.get(Constants_AuthorityGroup.msgFieldName_inputData).getAsJsonObject().get("authorityGroupId").getAsString());
   			}
		} catch (Exception e) {
			resultCode = Constants_AuthorityGroup.resultCode_systemException;
			resultMessage = ExceptionUtil.getFullMessage(e);
			logger.log(Level.SEVERE, resultMessage);
		}
		finally {
			reply = new JsonObject();
			reply.addProperty(Constants.msgFieldName_txnId, txnId);
			reply.addProperty(Constants.msgFieldName_resultCode, resultCode);
			reply.addProperty(Constants.msgFieldName_resultMessage, resultMessage);

			logger.log(Level.INFO, String.format(Messages_AuthorityGroup.msg_endService, 
	   				txnId, 
	   				CLASS, 
	   				METHOD));
		}
		return reply;
    }	

	public JsonObject TXN_AuthorityGroup_viewAuthorityGroupList(
			SqlSession session,
			JsonObject request) {
		
		final String METHOD = new Exception().getStackTrace()[0].getMethodName();
		
		JsonObject reply = null;
		String resultCode = Constants_AuthorityGroup.resultCode_systemException;
		String resultMessage = Constants_AuthorityGroup.emptyString;
		String txnId = request.get(Constants.msgFieldName_inputData).getAsJsonObject().get(Constants.msgFieldName_txnId).getAsString();
		
   		logger.log(Level.INFO, String.format(Messages_AuthorityGroup.msg_startService, 
   				txnId, 
   				CLASS, 
   				METHOD));   	

   		List<HashMap<String, Object>> rows = null;
   		
   		try {
   			String systemCode = request.get(Constants_AuthorityGroup.msgFieldName_inputData).getAsJsonObject().get("systemCode").getAsString();
   			String authorityGroupId = MapUtil.getNullableString(request.get(Constants_AuthorityGroup.msgFieldName_inputData).getAsJsonObject(),"authorityGroupId");
   			
    		rows = TB_COR_AUTHORITY_GROUP_MST.select_01(
    				session,
    				txnId,
    				systemCode, 
    				"%" + authorityGroupId + "%");

    		JsonArray jAuthorityGroupList = new JsonArray();
    		
    		for(int rowIndex = 0; rowIndex < rows.size(); rowIndex++) {
    			JsonObject jRow = new JsonObject();
    			HashMap<String, Object> row = rows.get(rowIndex);
       			jRow.addProperty("authorityGroupId", MapUtil.getNullableString(row, "AUTHORITY_GROUP_ID"));
    			jRow.addProperty("authorityGroupName", MapUtil.getNullableString(row, "AUTHORITY_GROUP_NAME"));
    			
    			jAuthorityGroupList.add(jRow);
    		}
    		resultCode = Constants_AuthorityGroup.resultCode_success;
    		
    		reply = new JsonObject();
    		reply.addProperty(Constants.msgFieldName_txnId, txnId);
			reply.add("authorityGroupList", jAuthorityGroupList);
			reply.addProperty(Constants.msgFieldName_resultCode, resultCode);
			reply.addProperty(Constants.msgFieldName_resultMessage, resultMessage);
		} catch (Exception e) {
			resultCode = Constants_AuthorityGroup.resultCode_systemException;
			resultMessage = ExceptionUtil.getFullMessage(e);
			logger.log(Level.SEVERE, resultMessage);
		}
		finally {

			logger.log(Level.INFO, String.format(Messages_AuthorityGroup.msg_endService, 
	   				txnId, 
	   				CLASS, 
	   				METHOD));
		}
		return reply;
    }	
	
	public class Constants_AuthorityGroup extends Constants {
	}	

	public static class Messages_AuthorityGroup extends Messages {
		public static String msg_alreadyExistAuthorityGroup = "The authorityGroup [%s] already exist.";
		public static String msg_notExistAuthorityGroup = "The authorityGroup [%s] not exist.";
	}	
}
